apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-checkpoint-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-ml-results
  labels:
    app: ml-analyzer
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ml-analyzer
  template:
    metadata:
      labels:
        app: ml-analyzer
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: analyzer
        image: alexis90024/ccc_assn2_docker_repo:ml-model
        imagePullPolicy: Always
        env:
        - name: ES_URL
          value: "https://elasticsearch-es-http.elastic.svc.cluster.local:9200"
        - name: POLL_INTERVAL_SECONDS
          value: "300"
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: es-secrets
              key: es-user
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: es-secrets
              key: es-pwd
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
            ephemeral-storage: "5Gi"
          limits:
            memory: "8Gi"
            cpu: "2"
            ephemeral-storage: "8Gi"
        volumeMounts:
        - name: checkpoint-storage
          mountPath: /app/checkpoints # the path inside the container where the checkpoint will be stored
      volumes:
      - name: checkpoint-storage
        persistentVolumeClaim:
          claimName: ml-checkpoint-pvc